language: node_js

node_js:
  - 10

before_script:
  - echo "Start CI"

install:
  - yarn install --check-files

script:
  - yarn run lint
  - yarn run build
  - yarn run test:coverage:report

before_deploy:
  - if [ ! -d dist ]; then yarn run build ; fi

deploy:
  provider: npm
  email: $NPM_AUTHOR_EMAIL
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
